export const GOOGLE_TRANSLATE_LANGUAGES = [
  { code: 'en', englishName: 'English', nativeName: 'English' },
  { code: 'hi', englishName: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'af', englishName: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'sq', englishName: 'Albanian', nativeName: 'Shqip' },
  { code: 'am', englishName: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'ar', englishName: 'Arabic', nativeName: 'العربية' },
  { code: 'hy', englishName: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'as', englishName: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'ay', englishName: 'Aymara', nativeName: 'Aymar aru' },
  { code: 'az', englishName: 'Azerbaijani', nativeName: 'Azərbaycan' },
  { code: 'bm', englishName: 'Bambara', nativeName: 'Bamanankan' },
  { code: 'eu', englishName: 'Basque', nativeName: 'Euskara' },
  { code: 'be', englishName: 'Belarusian', nativeName: 'Беларуская' },
  { code: 'bn', englishName: 'Bengali', nativeName: 'বাংলা' },
  { code: 'bho', englishName: 'Bhojpuri', nativeName: 'भोजपुरी' },
  { code: 'bs', englishName: 'Bosnian', nativeName: 'Bosanski' },
  { code: 'bg', englishName: 'Bulgarian', nativeName: 'Български' },
  { code: 'ca', englishName: 'Catalan', nativeName: 'Català' },
  { code: 'ceb', englishName: 'Cebuano', nativeName: 'Cebuano' },
  { code: 'zh-CN', englishName: 'Chinese (Simplified)', nativeName: '中文 (简体)' },
  { code: 'zh-TW', englishName: 'Chinese (Traditional)', nativeName: '中文 (繁體)' },
  { code: 'co', englishName: 'Corsican', nativeName: 'Corsu' },
  { code: 'hr', englishName: 'Croatian', nativeName: 'Hrvatski' },
  { code: 'cs', englishName: 'Czech', nativeName: 'Čeština' },
  { code: 'da', englishName: 'Danish', nativeName: 'Dansk' },
  { code: 'dv', englishName: 'Dhivehi', nativeName: 'ދިވެހިބަސް' },
  { code: 'doi', englishName: 'Dogri', nativeName: 'डोगरी' },
  { code: 'nl', englishName: 'Dutch', nativeName: 'Nederlands' },
  { code: 'eo', englishName: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'et', englishName: 'Estonian', nativeName: 'Eesti' },
  { code: 'ee', englishName: 'Ewe', nativeName: 'Eʋegbe' },
  { code: 'fil', englishName: 'Filipino (Tagalog)', nativeName: 'Filipino' },
  { code: 'fi', englishName: 'Finnish', nativeName: 'Suomi' },
  { code: 'fr', englishName: 'French', nativeName: 'Français' },
  { code: 'fy', englishName: 'Frisian', nativeName: 'Frysk' },
  { code: 'gl', englishName: 'Galician', nativeName: 'Galego' },
  { code: 'ka', englishName: 'Georgian', nativeName: 'ქართული' },
  { code: 'de', englishName: 'German', nativeName: 'Deutsch' },
  { code: 'el', englishName: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'gn', englishName: 'Guarani', nativeName: 'Avañe\'ẽ' },
  { code: 'gu', englishName: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ht', englishName: 'Haitian Creole', nativeName: 'Kreyòl ayisyen' },
  { code: 'ha', englishName: 'Hausa', nativeName: 'Hausa' },
  { code: 'haw', englishName: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi' },
  { code: 'iw', englishName: 'Hebrew', nativeName: 'עברית' },
  { code: 'hmn', englishName: 'Hmong', nativeName: 'Hmoob' },
  { code: 'hu', englishName: 'Hungarian', nativeName: 'Magyar' },
  { code: 'is', englishName: 'Icelandic', nativeName: 'Íslenska' },
  { code: 'ig', englishName: 'Igbo', nativeName: 'Igbo' },
  { code: 'ilo', englishName: 'Ilocano', nativeName: 'Ilokano' },
  { code: 'id', englishName: 'Indonesian', nativeName: 'Indonesia' },
  { code: 'ga', englishName: 'Irish', nativeName: 'Gaeilge' },
  { code: 'it', englishName: 'Italian', nativeName: 'Italiano' },
  { code: 'ja', englishName: 'Japanese', nativeName: '日本語' },
  { code: 'jv', englishName: 'Javanese', nativeName: 'Basa Jawa' },
  { code: 'kn', englishName: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'kk', englishName: 'Kazakh', nativeName: 'Қазақ тілі' },
  { code: 'km', englishName: 'Khmer', nativeName: 'ខ្មែរ' },
  { code: 'rw', englishName: 'Kinyarwanda', nativeName: 'Ikinyarwanda' },
  { code: 'gom', englishName: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'ko', englishName: 'Korean', nativeName: '한국어' },
  { code: 'kri', englishName: 'Krio', nativeName: 'Krio' },
  { code: 'ku', englishName: 'Kurdish (Kurmanji)', nativeName: 'Kurdî' },
  { code: 'ckb', englishName: 'Kurdish (Sorani)', nativeName: 'کوردی' },
  { code: 'ky', englishName: 'Kyrgyz', nativeName: 'Кыргызча' },
  { code: 'lo', englishName: 'Lao', nativeName: 'ລາວ' },
  { code: 'la', englishName: 'Latin', nativeName: 'Latina' },
  { code: 'lv', englishName: 'Latvian', nativeName: 'Latviešu' },
  { code: 'ln', englishName: 'Lingala', nativeName: 'Lingála' },
  { code: 'lt', englishName: 'Lithuanian', nativeName: 'Lietuvių' },
  { code: 'lg', englishName: 'Luganda', nativeName: 'Luganda' },
  { code: 'lb', englishName: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
  { code: 'mk', englishName: 'Macedonian', nativeName: 'Македонски' },
  { code: 'mai', englishName: 'Maithili', nativeName: 'मैथिली' },
  { code: 'mg', englishName: 'Malagasy', nativeName: 'Malagasy' },
  { code: 'ms', englishName: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'ml', englishName: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mt', englishName: 'Maltese', nativeName: 'Malti' },
  { code: 'mi', englishName: 'Maori', nativeName: 'Te Reo Māori' },
  { code: 'mr', englishName: 'Marathi', nativeName: 'मराठी' },
  { code: 'mni-Mtei', englishName: 'Meiteilon (Manipuri)', nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ' },
  { code: 'lus', englishName: 'Mizo', nativeName: 'Mizo' },
  { code: 'mn', englishName: 'Mongolian', nativeName: 'Монгол' },
  { code: 'my', englishName: 'Myanmar (Burmese)', nativeName: 'မြန်မာ' },
  { code: 'ne', englishName: 'Nepali', nativeName: 'नेपाली' },
  { code: 'no', englishName: 'Norwegian', nativeName: 'Norsk' },
  { code: 'ny', englishName: 'Nyanja (Chichewa)', nativeName: 'Chichewa' },
  { code: 'or', englishName: 'Odia (Oriya)', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'om', englishName: 'Oromo', nativeName: 'Afaan Oromoo' },
  { code: 'ps', englishName: 'Pashto', nativeName: 'پښتو' },
  { code: 'fa', englishName: 'Persian', nativeName: 'فارسی' },
  { code: 'pl', englishName: 'Polish', nativeName: 'Polski' },
  { code: 'pt', englishName: 'Portuguese', nativeName: 'Português' },
  { code: 'pa', englishName: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'qu', englishName: 'Quechua', nativeName: 'Runasimi' },
  { code: 'ro', englishName: 'Romanian', nativeName: 'Română' },
  { code: 'ru', englishName: 'Russian', nativeName: 'Русский' },
  { code: 'sm', englishName: 'Samoan', nativeName: 'Gagana Sāmoa' },
  { code: 'sa', englishName: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'gd', englishName: 'Scots Gaelic', nativeName: 'Gàidhlig' },
  { code: 'nso', englishName: 'Sepedi', nativeName: 'Sepedi' },
  { code: 'sr', englishName: 'Serbian', nativeName: 'Српски' },
  { code: 'st', englishName: 'Sesotho', nativeName: 'Sesotho' },
  { code: 'sn', englishName: 'Shona', nativeName: 'ChiShona' },
  { code: 'sd', englishName: 'Sindhi', nativeName: 'سنڌي' },
  { code: 'si', englishName: 'Sinhala', nativeName: 'සිංහල' },
  { code: 'sk', englishName: 'Slovak', nativeName: 'Slovenčina' },
  { code: 'sl', englishName: 'Slovenian', nativeName: 'Slovenščina' },
  { code: 'so', englishName: 'Somali', nativeName: 'Soomaali' },
  { code: 'es', englishName: 'Spanish', nativeName: 'Español' },
  { code: 'su', englishName: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'sw', englishName: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'sv', englishName: 'Swedish', nativeName: 'Svenska' },
  { code: 'tl', englishName: 'Tagalog (Filipino)', nativeName: 'Tagalog' },
  { code: 'tg', englishName: 'Tajik', nativeName: 'Тоҷикӣ' },
  { code: 'ta', englishName: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'tt', englishName: 'Tatar', nativeName: 'Татар' },
  { code: 'te', englishName: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'th', englishName: 'Thai', nativeName: 'ไทย' },
  { code: 'ti', englishName: 'Tigrinya', nativeName: 'ትግርኛ' },
  { code: 'ts', englishName: 'Tsonga', nativeName: 'Xitsonga' },
  { code: 'tr', englishName: 'Turkish', nativeName: 'Türkçe' },
  { code: 'tk', englishName: 'Turkmen', nativeName: 'Türkmen' },
  { code: 'tw', englishName: 'Twi', nativeName: 'Twi' },
  { code: 'uk', englishName: 'Ukrainian', nativeName: 'Українська' },
  { code: 'ur', englishName: 'Urdu', nativeName: 'اردو' },
  { code: 'ug', englishName: 'Uyghur', nativeName: 'ئۇيغۇرچە' },
  { code: 'uz', englishName: 'Uzbek', nativeName: 'Oʻzbek' },
  { code: 'vi', englishName: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'cy', englishName: 'Welsh', nativeName: 'Cymraeg' },
  { code: 'xh', englishName: 'Xhosa', nativeName: 'isiXhosa' },
  { code: 'yi', englishName: 'Yiddish', nativeName: 'ייִדיש' },
  { code: 'yo', englishName: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'zu', englishName: 'Zulu', nativeName: 'isiZulu' }
];

